nelmio_api_doc:
  documentation:
    info:
      title: Logbook API
      description: RESTful API for the logbook project
      version: 1.0.0
      x-build:
  areas: # to filter documented areas
    path_patterns:
      - ^/api/v1/(?!/doc$) # Accepts routes under /api except /api/doc
