name: logbook-api

services:
    logbook-api-nginx:
        container_name: logbook-api-nginx
        build:
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./:/app
        ports:
            - 8080:80
        depends_on:
            - logbook-api-fpm
        networks:
            - logbook-network

    logbook-api-fpm:
        container_name: logbook-api-fpm
        build:
            dockerfile: docker/php/fpm/Dockerfile
        env_file:
            - .env.local
        volumes:
            - ./:/app
        networks:
            - logbook-network

    logbook-api-database:
        container_name: symfony-base-api-database
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        volumes:
            - pgdata:/var/lib/postgresql/data

networks:
    logbook-network:

volumes:
    pgdata:
