name: logbook-api

services:
    logbook-api-nginx:
        container_name: logbook-api-nginx
        build:
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./:/app
        ports:
            - 8080:80
        depends_on:
            - logbook-api-fpm
        networks:
            - logbook-network

    logbook-api-fpm:
        container_name: logbook-api-fpm
        build:
            dockerfile: docker/php/fpm/Dockerfile
        env_file:
            - .env.local
        volumes:
            - ./:/app
        networks:
            - logbook-network

    logbook-api-database:
        container_name: logbook-api-database
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        volumes:
            - pgdata:/var/lib/postgresql/data

    logbook-api-adminer:
        container_name: logbook-api-adminer
        image: adminer
        environment:
            ADMINER_DEFAULT_DB_DRIVER: pgsql
            ADMINER_DEFAULT_DB_HOST: ${DATABASE_HOST}
            ADMINER_DEFAULT_DB_NAME: ${DATABASE_NAME}
        ports:
            - 8088:8080

networks:
    logbook-network:

volumes:
    pgdata:
