name: logbook-api

services:
    logbook-api-nginx:
        container_name: logbook-api-nginx
        build:
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./:/app
        ports:
            - 8080:80
        depends_on:
            - logbook-api-fpm
        networks:
            - logbook-network

    logbook-api-fpm:
        container_name: logbook-api-fpm
        build:
            dockerfile: docker/php/fpm/Dockerfile
        volumes:
            - ./:/app
        networks:
            - logbook-network

networks:
    logbook-network:
