controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  prefix: /api/v1
  type: attribute

app.swagger_ui:
  path: /api/v1/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
